### ISSUE TITLE
Install / usage info in readme

### ISSUE THREAD

**Issue by purplefish32** [Ore4444/justGage-package#2]
Hello,

Could you please write up a little documentation in the readme file (installation / usage) ?

I am very eager to test this plugin.

 Have a nice day.

**Comment by Ore4444** [comment]
It's a Meteor Smart Package. I think what you're looking for is docs for Meteorite: https://github.com/oortcloud/meteorite/

Use this command to install this package:
`mrt add justgage-package`

Did I miss anything?

**Comment by purplefish32** [comment]
I got that far, its the rest I am worried about :)
Can you provide a simple usage example ?

**Comment by Ore4444** [comment]
I don't know...
I used it long ago on with a codebase I have no access to anymore.
Where exactly are you getting stuck?
