### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by seiyria** [Ore4444/justGage-package#3]
after doing `mrt install justgage-package` meteor keeps telling me `JustGage is not defined` when I try to use it in the webpage.

**Comment by driblet** [comment]
I'm also getting this error, do we need to install anything else?

**Comment by seiyria** [comment]
I eventually got it installed, but Raphael kept complaining. I found [this](http://bernii.github.io/gauge.js/) as a result and it works just fine for me. I'll leave this open until this gets fixed though.

**Comment by driblet** [comment]
Great i'll check it out but it would be too much to ask if you can direct me to some example with code of how to use it? Thanks

**Comment by seiyria** [comment]
The only examples I had were on that page and digging through his code unfortunately.
